//Write a C program to generate machine code from an abstract syntax tree generated by the parser.

#include <stdio.h>
#include <stdlib.h>

// Define node types for the abstract syntax tree
typedef enum {
    OPERATOR_ADD,
    OPERATOR_SUB,
    OPERATOR_MUL,
    OPERATOR_DIV,
    OPERAND_CONST
} NodeType;

// Define the structure for nodes in the abstract syntax tree
typedef struct Node {
    NodeType type;
    int value;  // For operands
    struct Node *left;
    struct Node *right;
} Node;

// Function to create a new node
Node *createNode(NodeType type, int value, Node *left, Node *right) {
    Node *node = (Node *)malloc(sizeof(Node));
    node->type = type;
    node->value = value;
    node->left = left;
    node->right = right;
    return node;
}

// Function to generate machine code recursively from the AST
void generateMachineCode(Node *root) {
    if (root == NULL) {
        return;
    }

    if (root->type == OPERAND_CONST) {
        printf("PUSH %d\n", root->value); // Push the constant onto the stack
    } else {
        generateMachineCode(root->left); // Process left subtree
        generateMachineCode(root->right); // Process right subtree

        // Perform the operation based on the operator type
        switch (root->type) {
            case OPERATOR_ADD:
                printf("ADD\n");
                break;
            case OPERATOR_SUB:
                printf("SUB\n");
                break;
            case OPERATOR_MUL:
                printf("MUL\n");
                break;
            case OPERATOR_DIV:
                printf("DIV\n");
                break;
            default:
                fprintf(stderr, "Unknown operator type\n");
                exit(EXIT_FAILURE);
        }
    }
}

// Function to delete the AST
void deleteTree(Node *root) {
    if (root != NULL) {
        deleteTree(root->left);
        deleteTree(root->right);
        free(root);
    }
}

int main() {
    // Example AST for the expression: (2 * (3 + 4)) - 5
    Node *root = createNode(OPERATOR_SUB,
                             0, // Value is not used for operators
                             createNode(OPERATOR_MUL, 0,
                                        createNode(OPERAND_CONST, 2, NULL, NULL),
                                        createNode(OPERATOR_ADD, 0,
                                                   createNode(OPERAND_CONST, 3, NULL, NULL),
                                                   createNode(OPERAND_CONST, 4, NULL, NULL))),
                             createNode(OPERAND_CONST, 5, NULL, NULL));

    // Generate machine code from the AST
    generateMachineCode(root);

    // Clean up the memory used by the AST
    deleteTree(root);

    return 0;
}
